CREATE TABLE IF NOT EXISTS misturinhas (
  id           SERIAL       PRIMARY KEY,
  titulo       VARCHAR(200) NOT NULL,
  categoria    VARCHAR(50)  NOT NULL DEFAULT 'cabelo',
  aplicacao    TEXT,
  resultado    TEXT,
  ingredientes JSONB        NOT NULL DEFAULT '[]',
  ordem        SMALLINT     DEFAULT 0,
  ativo        BOOLEAN      DEFAULT TRUE,
  created_at   TIMESTAMPTZ  DEFAULT NOW()
);

INSERT INTO misturinhas (titulo, categoria, aplicacao, resultado, ingredientes, ordem) VALUES
  ('Cabelo com brilho natural', 'cabelo',
   'Aplique no couro cabeludo com massagens suaves, espalhe ao longo dos fios, deixe agir durante a noite e enxágue no dia seguinte.',
   'Fios mais nutridos, macios e com um brilho de arrasar.',
   '[{"qty":"1 tampa","product_id":"oleo-coco","nome":"Óleo de Coco"},{"qty":"1 tampa","product_id":"oleo-ricino","nome":"Óleo de Rícino"},{"qty":"7 gotas","product_id":"oleo-alecrim","nome":"Óleo de Alecrim"}]',
   1),
  ('Hidratação nutritiva', 'cabelo',
   'Aplique nos fios úmidos evitando a raiz. Deixe agir por 20–30 minutos com touca e enxágue.',
   'Cabelos mais fortes, hidratados e brilhantes.',
   '[{"qty":"1 colher","product_id":"oleo-abacate","nome":"Óleo de Abacate"},{"qty":"1 colher","product_id":"oleo-coco","nome":"Óleo de Coco"},{"qty":"1 colher","product_id":"glicerina","nome":"Glicerina Sobral"}]',
   2),
  ('Lavagem revitalizante', 'cabelo',
   'Adicione ao seu shampoo favorito. Massageie o couro cabeludo durante a lavagem.',
   'Lavagem que nutre, estimula o crescimento e deixa o cabelo com mais brilho.',
   '[{"qty":"1 tampa","product_id":"oleo-babosa","nome":"Óleo de Babosa"},{"qty":"1 tampa","product_id":"oleo-alecrim","nome":"Óleo de Alecrim"}]',
   3),
  ('Pré-hidratação potente', 'cabelo',
   'Aplique nos fios úmidos antes da máscara. Deixe 3 min, depois aplique a máscara por cima.',
   'Cabelos nutridos, macios e com brilho duradouro.',
   '[{"qty":"1 colher","product_id":"oleo-abacate","nome":"Óleo de Abacate"},{"qty":"1 colher","product_id":"oleo-uva","nome":"Óleo de Semente de Uva"}]',
   4),
  ('Umectação fortalecedora', 'cabelo',
   'Misture e aplique nos cabelos secos, enluvando mecha por mecha. Deixe agir durante a noite.',
   'Fios mais fortes, nutridos e com mais brilho.',
   '[{"qty":"A gosto","product_id":"oleo-ricino","nome":"Óleo de Rícino"},{"qty":"A gosto","product_id":"oleo-coco","nome":"Óleo de Coco"},{"qty":"A gosto","product_id":"oleo-argan","nome":"Óleo de Argan"}]',
   5),
  ('Pele mais radiante', 'pele',
   'Adicione ao seu creme clareador favorito. Use diariamente conforme orientação do creme base.',
   'Tom da pele uniforme, marcas suavizadas e mais viço.',
   '[{"qty":"Algumas gotas","product_id":"rosa-mosqueta-gotas","nome":"Óleo de Rosa Mosqueta"}]',
   1),
  ('Pós-barba suavizante', 'pele',
   'Após o barbear, aplique na pele limpa ou no creme pós-barba.',
   'Pele calma, macia, sem irritações.',
   '[{"qty":"A gosto","product_id":"oleo-karite","nome":"Óleo de Karité"},{"qty":"A gosto","product_id":"oleo-coco","nome":"Óleo de Coco"}]',
   2),
  ('Hidratação para as mamães', 'pele',
   'Misture em frasco limpo. Aplique na barriga, seios e coxas 1–2 vezes ao dia.',
   'Pele elástica, hidratada, com prevenção de estrias.',
   '[{"qty":"1 tampa","product_id":"oleo-amendoas","nome":"Óleo de Amêndoas"},{"qty":"1 tampa","product_id":"oleo-girassol","nome":"Óleo de Girassol"}]',
   3),
  ('Super óleo de banho', 'pele',
   'Agite bem em frasco limpo e aplique na pele úmida após ou durante o banho.',
   'Hidratação intensa com toque suave de perfume.',
   '[{"qty":"2 tampas","product_id":"oleo-amendoas","nome":"Óleo de Amêndoas"},{"qty":"1 tampa","product_id":"oleo-uva","nome":"Óleo de Semente de Uva"}]',
   4),
  ('Calmante natural', 'pele',
   'Aplique direto na pele após depilação ou em áreas com coceira.',
   'Alívio rápido para irritações e coceiras.',
   '[{"qty":"1 colher","product_id":"oleo-coco","nome":"Óleo de Coco"},{"qty":"1 colher","product_id":"oleo-copaiba","nome":"Óleo de Copaíba"}]',
   5);
